test:
  uri: lb://cliente-service
  uri2: lb://reclamo-service
  uri3: lb://producto-service

spring:
  application:
    name: gateway

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      enabled: true
  instance:
    prefer-ip-address: true
